### ISSUE TITLE
Error when trying to run this project

### ISSUE THREAD

**Issue by jesslawnz** [zach-hopkins/create-t3svelte-app#27]
Not sure what to say - when I build this with 
```
npx create-t3svelte-app@latest  
```
( Windows 10) 

I receive the following : 

```console
VITE v3.2.5  ready in 1963 ms

  ➜  Local:   http://localhost:5174/
  ➜  Network: use --host to expose
file:///C:/test2/node_modules/@sveltejs/kit/src/exports/node/index.js:108
        const headers = Object.fromEntries(response.headers);
                               ^

TypeError: undefined is not iterable
    at Function.fromEntries (<anonymous>)
    at setResponse (file:///C:/test2/node_modules/@sveltejs/kit/src/exports/node/index.js:108:25)
    at file:///C:/test2/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:523:6

Node.js v18.12.1
```

highlighting line 523 here:
```
				if (rendered.status === 404) {
					// @ts-expect-error
					serve_static_middleware.handle(req, res, () => {
						setResponse(res, rendered);
					});
				} else {
>>>>>                          setResponse(res, rendered);
				}
			} catch (e) {
				const error = coalesce_to_error(e);
				res.statusCode = 500;
				res.end(fix_stack_trace(error));
			}
		});
	};
}
```

(Seems to happen regardless of project configuration options, both with/without db config. I am trying to create a typescript + tRPC + Prisma configuration

**Comment by zach-hopkins** [comment]
Thanks, I will take a look at this today along with some other open issues. With SvelteKit 1.0 coming out it's a good time to make some important changes to t3svelte
