### ISSUE TITLE
Vite version dependency issue

### ISSUE THREAD

**Issue by joshua1** [zach-hopkins/create-t3svelte-app#31]
![Uploading Screenshot 2022-12-27 at 5.27.53 PM.png…]()
it seems like a dependency version upgrade is needed there is a 3.2/3.1 versions of vite

**Comment by L-Mario564** [comment]
I'm unable to view your screenshot

**Comment by joshua1** [comment]
```
 ✖ Copy project files
    → npm ERR!     /Users/abjo311/.npm/_logs/2022-12-27T15_25_48_713Z-debug-0.log
    Initialize git
    Install dependencies
    Initialize DB
node:internal/errors:863
  const err = new Error(message);
              ^

Error: Command failed: npm install --save --package-lock-only --no-package-lock @trpc/client@"^9.27.2" @trpc/server@"^9.27.2" trpc-sveltekit trpc-transformer zod && npm install --save -D --package-lock-only --no-package-lock @prisma/client prisma
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: t3svelte-app@0.0.1
npm ERR! Found: vite@3.2.5
npm ERR! node_modules/vite
npm ERR!   dev vite@"^3.1.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^4.0.0" from @sveltejs/kit@1.0.0-next.589
npm ERR! node_modules/@sveltejs/kit
npm ERR!   dev @sveltejs/kit@"next" from the root project
npm ERR!   peer @sveltejs/kit@"^1.0.0-next.587" from @sveltejs/adapter-auto@1.0.0-next.91
npm ERR!   node_modules/@sveltejs/adapter-auto
npm ERR!     dev @sveltejs/adapter-auto@"next" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/abjo311/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/abjo311/.npm/_logs/2022-12-27T15_25_48_713Z-debug-0.log
```
@L-Mario564

**Comment by L-Mario564** [comment]
Pretty sure this has been fixed but the publish workflow failed.
@zach-hopkins Can you bump the version to solve this issue?

**Comment by zach-hopkins** [comment]
Should be fixed with version bump. Thanks @L-Mario564 and @joshua1

**Comment by joshua1** [comment]
@zach-hopkins while the dependency version issue is sorted, there still is another issue 
```
 VITE v4.0.3  ready in 702 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
file:///Users/abjo311/Documents/ShiftLabs/Projects/trpc/node_modules/@sveltejs/kit/src/exports/node/index.js:108
        const headers =Object && Object?.fromEntries(response.headers);
                                         ^

TypeError: undefined is not iterable
    at Function.fromEntries (<anonymous>)
    at setResponse (file:///Users/abjo311/Documents/ShiftLabs/Projects/trpc/node_modules/@sveltejs/kit/src/exports/node/index.js:108:35)
    at file:///Users/abjo311/Documents/ShiftLabs/Projects/trpc/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:511:6

Node.js v18.9.0
 ELIFECYCLE  Command failed with exit code 1.
```
with both npm and pnpm i got the issue above. I do not see it with a clean set up of sveltekit 1.0 using 
```
npm create svelte@latest
```
however , when i added the trpc implementation following the source generated here , i got thesame error as above.
