### ISSUE TITLE
'Undefined' error on default options on Mac

### ISSUE THREAD

**Issue by zach-hopkins** [zach-hopkins/create-t3svelte-app#9]
```
? Please choose which project template to use Standard
? Initialize a git repository? No
? Automatically install dependencies? No
? Initialize Postgres DB w/ Prisma? (Requires DB URI String) No

file:///Users/mac-suer/.npm/_npx/5be47aec1dfa4302/node_modules/create-t3svelte-app/src/cli.js:98
      dbString: '' || dbAnswers.dbString
                                ^

TypeError: Cannot read properties of undefined (reading 'dbString')
    at promptForMissingOptions (file:///Users/ajcwebdev/.npm/_npx/5be47aec1dfa4302/node_modules/create-t3svelte-app/src/cli.js:98:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async cli (file:///Users/ajcwebdev/.npm/_npx/5be47aec1dfa4302/node_modules/create-t3svelte-app/src/cli.js:104:16)
```

Can't reproduce in linux - could have something to do with null string in the object:

```
if (answers.db && requireURI) 
  var dbAnswers = await inquirer.prompt(dbQuestions)

//Handle Empty Options
else var dbAnswers = {dbString: ''}
if (!dbSolutionAnswers) var dbSolutionAnswers = {dbSolution: ''}
```

Can dig into this a little later, probably something stupid

**Comment by megadrive** [comment]
Also occurring on Windows:

```
? Please choose which project template to use Standard
? Initialize a git repository? No
? Automatically install dependencies? No
? Initialize Postgres DB w/ Prisma? (Requires DB URI String) No
file:///C:/Users/.../AppData/Local/npm-cache/_npx/8f568aeeec8b9376/node_modules/create-t3svelte-app/src/cli.js:98
      dbString: '' || dbAnswers.dbString
                                ^

TypeError: Cannot read properties of undefined (reading 'dbString')
    at promptForMissingOptions (file:///C:/Users/.../AppData/Local/npm-cache/_npx/8f568aeeec8b9376/node_modules/create-t3svelte-app/src/cli.js:98:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async cli (file:///C:/Users/.../AppData/Local/npm-cache/_npx/8f568aeeec8b9376/node_modules/create-t3svelte-app/src/cli.js:104:16)
```

**Comment by zach-hopkins** [comment]
Oof, had the package.json pointed to the wrong registry for updates. Awkward. Should be actually resolved now resolved now.
